pipeline:
  frontend:
    image: microsoft/aspnetcore-build:2.0.0
    commands:
      - cd when.Web
      - npm install
      - npm run build

  backend:
    image: microsoft/aspnetcore-build:2.0.0
    commands: 
      - cd when.ApiServer
      - mkdir -p wwwroot
      - cp -r ../when.Web/dist/* wwwroot/
      - mkdir -p out
      - dotnet restore
      - dotnet publish --output out/ --configuration Release

  docker:
    image: plugins/docker
    repo: lowet84/when
    secrets: [ docker_username, docker_password ]
    tags: latest