pipeline:
  frontend:
    image: microsoft/aspnetcore-build:2.0.0
    commands:
      - cd when.Web
      - npm install
      - npm run build
      - cp dist/* ../when.ApiServer/wwwroot/

  backend:
    image: microsoft/aspnetcore-build:2.0.0
    commands: 
      - cd when.ApiServer
      - mkdir -p out
      - dotnet restore
      - dotnet publish --output out/ --configuration Release
