pipeline:
  frontend:
    image: microsoft/aspnetcore-build:2.0.0
    commands:
      - cd when.Web
      - npm install
      - npm run dev
      - ls

  backend:
    image: microsoft/aspnetcore-build:2.0.0
    commands: 
      - ls
#      - mkdir -p out
#      - dotnet restore
#      - dotnet publish --output out/ --configuration Release
