pipeline:
  frontend:
    image: microsoft/aspnetcore-build:2.0.0
    commands:
      - cd when.Web
      - npm install
      - npm run build

  backend:
    image: microsoft/aspnetcore-build:2.0.0
    commands: 
      - cd when.ApiServer
      - mkdir -p wwwroot
      - cp ../when.Web/dist/* wwwroot/
      - mkdir -p out
      - dotnet restore
      - dotnet publish --output out/ --configuration Release
