pipeline:
  build:
    image: microsoft/aspnetcore-build:2.0.0
    commands: 
      - mkdir -p out
      - dotnet restore
      - dotnet publish --output out/ --configuration Release
  evaluate:
    image: alpine
    commands:
      - ls
