pipeline:
  frontend:
    image: microsoft/aspnetcore-build:2.0.0
    commands:
      - cd when.Web
      - npm install
      - npm run build

  backend:
    image: microsoft/aspnetcore-build:2.0.0
    commands: 
      - cd when.ApiServer
      - mkdir -p wwwroot
      - cp -r ../when.Web/dist/* wwwroot/
      - mkdir -p out
      - dotnet restore
      - dotnet publish --output out/ --configuration Release
      - mv out ..

  docker:
    image: plugins/docker
    repo: lowet84/when
    secrets: [ docker_username, docker_password ]
    tags: latest
    when:
      branch: master

  deploy:
    image: appleboy/drone-ssh
    host: home.local
    username: root
    secrets: [ ssh_key ]
    port: 22
    script:
      - cd homeserver2/when
      - upgrade-compose